const sequelize=require("../util/database");
const {DataTypes}=require("sequelize");

const Profiles=sequelize.define("profiles",{
    id:{
        type:DataTypes.INTEGER,
        autoIncrement:true,
        primaryKey:true
    },
    username:{
        type:DataTypes.STRING,
        allowNull:false,
        unique:true,
    },
    name:{
        type:DataTypes.STRING,
        allowNull:true,
    },
    type:{
        type:DataTypes.STRING,
        allowNull:true,
    },
    email:{
        type:DataTypes.STRING,
        allowNull:true,
        unique:true,
    },
    company:{
        type:DataTypes.STRING,
        allowNull:true,
    },
    bio:{
        type:DataTypes.STRING,
        allowNull:true,
    },
    location:{
        type:DataTypes.STRING,
        allowNull:true,
    },
    avatar_url:{
        type:DataTypes.STRING,
        allowNull:true,
    },
    html_url:{
        type:DataTypes.STRING,
        allowNull:true,
    },
    public_repos:{
        type:DataTypes.INTEGER,
        DefaultValue:0,
    },
    public_gists:{
        type:DataTypes.INTEGER,
        DefaultValue:0,
    },
    followers:{
        type:DataTypes.INTEGER,
        defaultValue:0,
    },
    following:{
        type:DataTypes.INTEGER,
        defaultValue:0,
    },
    accountCreatedAt:{
        type:DataTypes.DATE,
        allowNull:true,
    },
    accountUpdateAt:{
        type:DataTypes.DATE,
        allowNull:true,
    },
    
});

module.exports=Profiles;